version: 2.1
jobs:
  # runnnig commands on basic image
  Hello-World:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: hiroakisuzuki
          password: $DOCKERHUB_PASSWORD

    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: hiroakisuzuki
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Getting the code
          command: |
            ls -al
            echo '^^^The files in your repo^^^'
  Using-Node:
    docker:
      - image: cimg/node:17.2
        auth:
          username: hiroakisuzuki
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-World
      - Using-Node:
          requires:
            - Fetch-Code

